default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: ec2-54-235-249-33.compute-1.amazonaws.com
  database: dcr9blr4falvss
  username: rrthvuadodrqet
  password: 25e9aafa4bb704abbe52fa4d0cc57158f76db3b51f10f625828e781a61e94228

test:
  <<: *default
  host: ec2-23-23-92-179.compute-1.amazonaws.com
  database: d8qcsgvb1kd9o4
  username: hazxllxrybwclv
  password: f01c2ec942f03ab2f0474d17ae4ac4193ef5f1f6f28aeef8cc5f70c79f603dad

production:
  <<: *default
  database: desafio-desenvolvedores_production
  username: desafio-desenvolvedores
  password: <%= ENV['DESAFIO-DESENVOLVEDORES_DATABASE_PASSWORD'] %>
