# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd0b5011fb63828f304182993b649a396d8b31c1d75a8a6f3d4117eeac50e73fead61c5ff7e8446ba4b08ec27c82be30174b8d9959d42c91606be5bd95e454fe

test:
  secret_key_base: 7511ddca5f17ad7f7a26f61e10aeef0d5919ada5415986aaff4977ef74fce703ba5ee1b7b8201e539d60e00004b20f5bc865167a8e40521073ac197ac3dfc295

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
