user_name: 'app37378940@heroku.com'
password: '8-1b-4N59GT4FKMOTbdR9g'
address: 'smtp.mandrillapp.com'
domain: 'smtp.mandrillapp.com'
port: '587'

# user_name: '3643558d5397c51c1',
# password: '3c582e12d2598d',
# address: 'mailtrap.io',
# domain: 'mailtrap.io',
# port: '2525',
# authentication: :cram_md5
